export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const CART_ITEMS_RESET = "CART_ITEMS_RESET";

export const CART_SAVE_SHIPPING_DETAILS = "CART_SAVE_SHIPPING_DETAILS";
export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";